
import React, { useState } from 'react'
import '../app.css'

export default function Learn() {
    const [activeSection, setActiveSection] = useState(null);

    const carbonSections = [
        {
            title: "What is a Carbon Footprint?",
            content: (
                <>
                    <p>A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) generated by our actions. It encompasses:</p>
                    <ul>
                        <li>Direct emissions from personal activities</li>
                        <li>Indirect emissions from the production of goods and services we consume</li>
                        <li>Measured in metric tons of carbon dioxide equivalent (CO2e)</li>
                    </ul>
                    <p>The average global carbon footprint is approximately 4 tons per person annually, but in developed countries like the United States, it can be as high as 16 tons per person.</p>
                </>
            )
        },
        {
            title: "Detailed Breakdown of Carbon Emissions",
            content: (
                <>
                    <h4>Major Emission Sources</h4>
                    <div className="emission-breakdown">
                        <div className="emission-category">
                            <strong>Transportation (29%)</strong>
                            <ul>
                                <li>Personal vehicle use</li>
                                <li>Air travel</li>
                                <li>Public transportation</li>
                                <li>Shipping and logistics</li>
                            </ul>
                        </div>
                        <div className="emission-category">
                            <strong>Electricity & Heating (25%)</strong>
                            <ul>
                                <li>Home energy consumption</li>
                                <li>Industrial power generation</li>
                                <li>Fossil fuel power plants</li>
                                <li>Renewable energy alternatives</li>
                            </ul>
                        </div>
                        <div className="emission-category">
                            <strong>Food & Agriculture (24%)</strong>
                            <ul>
                                <li>Meat production</li>
                                <li>Dairy farming</li>
                                <li>Crop cultivation</li>
                                <li>Food transportation</li>
                            </ul>
                        </div>
                        <div className="emission-category">
                            <strong>Manufacturing & Construction (21%)</strong>
                            <ul>
                                <li>Industrial processes</li>
                                <li>Material production</li>
                                <li>Building construction</li>
                                <li>Consumer goods manufacturing</li>
                            </ul>
                        </div>
                    </div>
                </>
            )
        },
        {
            title: "Comprehensive Reduction Strategies",
            content: (
                <>
                    <div className="reduction-strategies">
                        <div className="strategy-category">
                            <h4>Personal Transportation</h4>
                            <ul>
                                <li>Use electric or hybrid vehicles</li>
                                <li>Bike or walk for short distances</li>
                                <li>Use public transportation</li>
                                <li>Carpool or use ride-sharing</li>
                                <li>Combine errands to reduce trips</li>
                            </ul>
                        </div>
                        <div className="strategy-category">
                            <h4>Home Energy Efficiency</h4>
                            <ul>
                                <li>Install solar panels</li>
                                <li>Use LED lighting</li>
                                <li>Improve home insulation</li>
                                <li>Use smart thermostats</li>
                                <li>Choose energy-efficient appliances</li>
                            </ul>
                        </div>
                        <div className="strategy-category">
                            <h4>Dietary Changes</h4>
                            <ul>
                                <li>Reduce meat consumption</li>
                                <li>Choose local and seasonal produce</li>
                                <li>Minimize food waste</li>
                                <li>Opt for plant-based proteins</li>
                                <li>Support sustainable agriculture</li>
                            </ul>
                        </div>
                        <div className="strategy-category">
                            <h4>Consumption & Waste</h4>
                            <ul>
                                <li>Practice the 3 Rs: Reduce, Reuse, Recycle</li>
                                <li>Buy second-hand items</li>
                                <li>Choose products with minimal packaging</li>
                                <li>Compost organic waste</li>
                                <li>Support circular economy brands</li>
                            </ul>
                        </div>
                    </div>
                </>
            )
        },
        {
            title: "Global Impact and Future Outlook",
            content: (
                <>
                    <p>Climate change is a critical global challenge. The Intergovernmental Panel on Climate Change (IPCC) warns that to limit global warming to 1.5°C above pre-industrial levels, we must:</p>
                    <ul>
                        <li>Reduce global carbon emissions by 45% by 2030</li>
                        <li>Achieve net-zero emissions by 2050</li>
                        <li>Transition to renewable energy sources</li>
                        <li>Implement sustainable urban planning</li>
                        <li>Protect and restore natural ecosystems</li>
                    </ul>
                    <p>Individual actions, when combined, can create significant systemic change and contribute to global sustainability efforts.</p>
                </>
            )
        }
    ];

    return (
        <div className="learn-carbon-container">

            <div className="what-carbon">
                <h2>Hmm.. I'm not sure about what Carbon FootPrints are 🤔</h2>
                <div className="what-carbon-txt">A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) that are generated by our actions.
                    The average carbon footprint for a person in the United States is 16 tons, one of the highest rates in the world. Globally, the average carbon footprint is closer to 4 tons. To have the best chance of avoiding a 2℃ rise in global temperatures, the average global carbon footprint per year needs to drop to under 2 tons by 2050.
                    Lowering individual carbon footprints from 16 tons to 2 tons doesn’t happen overnight! By making small changes to our actions, like eating less meat, taking fewer connecting flights and line drying our clothes, we can start making a big difference.</div>
            </div>
            <div className="learn-carbon-header">
                <h2>Comprehensive Guide to Carbon Footprints</h2>
                <p>Understanding and Reducing Your Environmental Impact</p>
            </div>

            <div className="carbon-sections">
                {carbonSections.map((section, index) => (
                    <div key={index} className="carbon-section">
                        <div
                            className="section-title"
                            onClick={() => setActiveSection(activeSection === index ? null : index)}
                        >
                            <h3>{section.title}</h3>
                            <span>{activeSection === index ? '−' : '+'}</span>
                        </div>
                        {activeSection === index && (
                            <div className="section-content">
                                {section.content}
                            </div>
                        )}
                    </div>
                ))}
            </div>
        </div>
    )
}