import React, { useState } from 'react'
import '../App.css'
import CarbonEmissionsReport from './CarbonEmissionReport';
export default function Learn() {
    const [activeSection, setActiveSection] = useState(null);



    return (
        <div className="learn-carbon-container">

            <div className="what-carbon">
                <h2>Hmm..I'm not sure about what Carbon FootPrints are 🤔</h2>
                <div className="what-carbon-txt">A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) that are generated by our actions.
                    The average carbon footprint for a person in the United States is 16 tons, one of the highest rates in the world. Globally, the average carbon footprint is closer to 4 tons. To have the best chance of avoiding a 2℃ rise in global temperatures, the average global carbon footprint per year needs to drop to under 2 tons by 2050.
                    Lowering individual carbon footprints from 16 tons to 2 tons doesn’t happen overnight! By making small changes to our actions, like eating less meat, taking fewer connecting flights and line drying our clothes, we can start making a big difference.
                    Key contributors to an individual's carbon footprint include:
                    Energy use (electricity, heating, and cooling).
                    Transportation (cars, airplanes, and public transit).
                    Diet choices (meat, dairy, and food waste).
                    Consumption patterns (clothing, electronics, and packaging).
                </div>
            </div>

            <CarbonEmissionsReport />

        </div>
    )
}